import { MetadataRoute } from 'next';
import { getTranslations } from 'next-intl/server';

// Single theme/background in manifest; `layout.tsx` `viewport.themeColor` handles light/dark chrome.
const BRAND_THEME_COLOR = '#1c69e3';
const BRAND_BACKGROUND_COLOR = '#fdfdfd';

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const t = await getTranslations({ locale: 'en', namespace: 'manifest' });

  return {
    id: '/',
    name: t('name'),
    short_name: t('shortName'),
    description: t('description'),
    lang: 'en',
    dir: 'ltr',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    theme_color: BRAND_THEME_COLOR,
    background_color: BRAND_BACKGROUND_COLOR,
    categories: ['business', 'productivity', 'photo', 'graphics'],
    icons: [
      {
        src: '/favicon.ico',
        sizes: '32x32',
        type: 'image/x-icon',
      },
      {
        src: '/logo/icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/logo/icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      // Opaque PWA icons only — not theme `icon-light/dark` (transparent; wrong for install surfaces). TODO: 512 maskable.
    ],
    // Build-time pre-rendered PNGs under `public/share/og/` (gitignored).
    // Generated by `scripts/build-og-images.ts` via `pnpm prebuild`.
    screenshots: [
      {
        src: '/share/og/home-v2.png',
        sizes: '1200x630',
        type: 'image/png',
        form_factor: 'wide',
        label: 'App Template — AI ad creative platform for e-commerce teams',
      },
      {
        src: '/share/og/feature-product-photo-v2.png',
        sizes: '1200x630',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Studio-grade product photos in seconds — no shoot required',
      },
      {
        src: '/share/og/feature-product-video-v2.png',
        sizes: '1200x630',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Campaign-ready product videos with on-brand control',
      },
      {
        src: '/share/og/feature-url-to-video-v2.png',
        sizes: '1200x630',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Paste a product URL — get an ad-ready video creative',
      },
      {
        src: '/share/og/feature-video-insight-v2.png',
        sizes: '1200x630',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Decode winning ad videos and reuse the patterns',
      },
    ],
    shortcuts: [
      {
        name: 'Open workspace',
        short_name: 'Workspace',
        description: 'Open App Template to create photo and video ad creatives',
        url: '/app',
        icons: [
          {
            src: '/logo/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
        ],
      },
      {
        name: 'View pricing',
        short_name: 'Pricing',
        description: 'Compare App Template plans and credit packs',
        url: '/pricing',
        icons: [
          {
            src: '/logo/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
        ],
      },
    ],
  };
}
