export const AUTH_RUNTIME = {
  OTP_LENGTH: 6,
  OTP_MAX_ATTEMPTS: 5,
  OTP_EXPIRES_SECONDS: 10 * 60,
  OTP_RESEND_COOLDOWN_MS: 60_000,
  SESSION_COOKIE_CACHE_MAX_AGE_SECONDS: 60,
} as const;

export const REALTIME_RUNTIME = {
  SSE_HEARTBEAT_MS: 25_000,
  VIDEO_INSIGHT_MESSAGES_SNAPSHOT_LIMIT: 50,
} as const;
